module.exports = {
    locations: {
        bountiful: "Bountiful Temple\n640 Bountiful Blvd,\nBountiful, UT 84010",
        jordan: "Jordan River Temple\n10200 S Temple Dr,\nSouth Jordan, UT 84095",
        sheraton: "Sheraton Hotel\n150 W 500 S,\nSalt Lake City, UT 84101",
        olympus: "Olympus High School\n4055 S 2300 E,\nHolladay, UT 84124",
        olympus: "Olympus High School\n4055 S 2300 E,\nHolladay, UT 84124",
    },
    rooms: {
        alta: "Alta",
        cottonwood: "Big Cottonwood",
        brighton: "Brighton",
        brighton_alta: "Brighton/Alta",
        deer: "Deer Valley",
        exec: "Executive Board",
        ballroom: "Grand Ballroom",
        arches: "Arches Ballroom",
        powder: "Powder Mountain",
        sidewinder: "Sidewinder",
        snowbird: "Snowbird",
        sundance: "Sundance",
        wasatch: "Wasatch",
        wildcat: "Wildcat",
    },
};
