module.exports = {
    gentri: { name: "Gentri" },
    emily_freeman: { name: "Emily Freeman" },
    david_butler: { name: "David Butler" },
    scott_and_becky_mackintosh: { name: "Scott and Becky Mackintosh" },
    becket_cook: { name: "Becket Cook" },
    ty_mansfield: { name: "Ty Mansfield" },
    jacob_hess: { name: "Jacob Hess" },
    carrie_skarda: { name: "Carrie Skarda" },
    debby_jackson: { name: "Debby Jackson" },
    dale_larsen: { name: "Dale Larsen" },
    rebecca_silva: { name: "Rebecca Silva" },
    janae_monsen: { name: "Janae Monsen" },
    patrice_fairbanks: { name: "Patrice Fairbanks" },
    victoria_adam: { name: "Victoria Adam" },
    lyndsey_andreasky: { name: "Lyndsey Andreasky" },
    chelsea_hanson: { name: "Chelsea Hanson" },
    sean_crandall: { name: "Sean Crandall" },
    jeff_case: { name: "Jeff Case" },
    shannon_rants: { name: "Shannon Rants" },
    becky_edwards: { name: "Becky Edwards" },
    vaughn_armstrong: { name: "Vaughn Armstrong" },
    bob_and_deb_stevens: { name: "Bob and Deb Stevens" },
    liv_and_matthew_haynes: { name: "Liv and Matthew Haynes" },
    charles_and_julee_hamilton: { name: "Charles and Julee Hamilton" },
    will_edgel: { name: "Will Edgel" },
    blake_smith: { name: "Blake Smith" },
    travis_steward: { name: "Travis Steward" },
    dennis_schleicher: { name: "Dennis Schleicher" },
    kim_shores: { name: "Kim Shores" },
    sarah_tate: { name: "Sarah Tate" },
    brandon_jensen: { name: "Brandon Jensen" },
    nick_gregory: { name: "Nick Gregory" },
    landon_phillips: { name: "Landon Phillips" },
    katherine_hermann: { name: "Katherine Hermann" },
    russ_gaede: { name: "Russ Gaede" },
    kurt_francom: { name: "Kurt Francom." },
    bryce_johnson: { name: "Bryce Johnson" },
    rick_hall: { name: "Rick Hall" },
    sita_kinikini: { name: "Sita Kinikini" },
    karen_dufresne: { name: "Karen Dufresne" },
    alex_lindstrom: { name: "Alex Lindstrom" },
    bradley_stoker: { name: "Bradley Stoker" },
    quinn_kelly: { name: "Quinn Kelly" },
    lucas_and_wyrlon_jones: { name: "Lucas and Wyrlon Jones" },
    monica_phillips: { name: "Monica Phillips" },
    wendy_eldredge: { name: "Wendy Eldredge" },
    maryann_broberg: { name: "Maryann Broberg" },
    jeff_bennion: { name: "Jeff Bennion" },
    michael_goodman: { name: "Michael Goodman" },
    richard_ostler: { name: "Richard Ostler" },
    brent_ebmeyer: { name: "Brent Ebmeyer" },
    joey_sheppard: { name: "Joey Sheppard" },
    myrna_moll: { name: "Myrna Moll" },
    robert_burgraaf: { name: "Robert Burgraaf" },
    tyler_lefevor: { name: "Tyler Lefevor" },
    dan_gray: { name: "Dan Gray" },
    karen_c_and_michael_edwards: { name: "Karen C. and Michael Edwards" },
    sherie_christensen: { name: "Sherie Christensen" },
    jarry_lozano: { name: "Jarry Lozano" },
    chad_hill: { name: "Chad Hill" },
    greg_reichmann: { name: "Greg Reichmann" },
    justin_mangum: { name: "Justin Mangum" },
    pret_dahlgren: { name: "Pret Dahlgren" },
    troy_dahlgren: { name: "Troy Dahlgren" },
    charlie_bird: { name: "Charlie Bird" },
    tami_and_ben_wright: { name: "Tami and Ben Wright" },
    ky_merkley: { name: "Ky Merkley" },
    brent_schindler: { name: "Brent Schindler" },
    jenn_curtis: { name: "Jenn Curtis" },
    lisa_hansen: { name: "Lisa Hansen" },
    david_ostler: { name: "David Ostler" },
    ryan_and_kerrie_warnick: { name: "Ryan and Kerrie Warnick" },
    erick_and_kathi_hacking: { name: "Erick and Kathi Hacking" },
    ricardo_and_elizabeth_rosas: { name: "Ricardo and Elizabeth Rosas" },
    lucas_jones: { name: "Lucas Jones" },
    ann_pack: { name: "Ann Pack" },
    kris_irvin: { name: "Kris Irvin" },
    allison_pryor: { name: "Allison Pryor" },
    lisa_arnold: { name: "Lisa Arnold" },
    tanya_bennion: { name: "Tanya Bennion" },
};
